<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('otp_verifications', function (Blueprint $table) {
            $table->id();

            // Company requesting the verification
            $table->foreignId('company_id')
                ->constrained('companies')
                ->cascadeOnDelete();

            // Customer receiving the OTP
            $table->foreignId('contact_id')
                ->nullable()
                ->constrained('contacts')
                ->nullOnDelete();

            // WhatsApp number used to send the OTP
            $table->foreignId('whatsapp_phone_number_id')
                ->nullable()
                ->constrained('whatsapp_phone_numbers')
                ->nullOnDelete();

            // Optional message that delivered the OTP
            $table->foreignId('message_id')
                ->nullable()
                ->constrained('messages')
                ->nullOnDelete();

            // Reference generated by the company's system
            $table->string('reference')->unique();

            // Phone number receiving the OTP
            $table->string('phone');

            // Never store the raw OTP
            $table->string('code_hash');

            // OTP status
            $table->enum('status', [
                'pending',
                'verified',
                'expired',
                'failed',
                'cancelled',
            ])->default('pending');

            // Number of verification attempts
            $table->unsignedTinyInteger('attempts')->default(0);

            // Maximum allowed attempts
            $table->unsignedTinyInteger('max_attempts')->default(5);

            // Expiration
            $table->timestamp('expires_at');

            // Verification timestamp
            $table->timestamp('verified_at')->nullable();

            // Optional cancellation timestamp
            $table->timestamp('cancelled_at')->nullable();

            // Additional information
            $table->json('metadata')->nullable();

            $table->timestamps();

            $table->index('company_id');
            $table->index('contact_id');
            $table->index('phone');
            $table->index('status');
            $table->index('expires_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('otp_verifications');
    }
};